#!/bin/bash
#
# adpn-ingest-test: Assemble information and run tests for a package of files staged for
# ingest as a LOCKSS Archival Unit, given a local location, a LOCKSS Plugin and parameters
# for the plugin.
#
# Switches can be provided on the command line, or interactively on the console at input
# prompts. You can set default values for commonly-repeated switches (for example, if your
# LOCKSS daemon is always at the same location, you won't need to re-enter that location
# every time you run the script) by creating a plaintext file called:
#
# 		./adpn-ingest-test.defaults.conf
#
# where the conf file is located in the same directory as the adpn-ingest-test script.
# The file should be a text/plain file, with one switch on each line of the file. If the
# same switch is provided on the command line, the value on the command line overrides the
# value provided in the defaults.conf file.
#
# Usage:
#
# 	adpn-ingest-test --local=<PATH>
#
# 		run without other parameters, the script will prompt on the console for AU title,
# 		publisher plugin, and LOCKSS Daemon information, report back the required
# 		parameters for the Publisher Plugin, and then allow the option to input parameters
# 		and perform a test of the accessibility of the start URL and/or manifest page for
# 		an HTTP GET.
#
# 	adpn-ingest-test [--daemon=<DAEMON> [--user=<USERNAME>] [--pass=<PASSWORD>]
# 		[--plugin=<NAME>|--plugin-id=<FQCN>|--plugin-regex=<PATTERN>]
#
# @version 2019.0610

##########################################################################################
### CONFIGURATION: Set up some constants #################################################
##########################################################################################

SCRIPTDIR=`dirname $0`
SCRIPT=`basename $0`
PATH=${SCRIPTDIR}:${PATH}
CONFFILE="${SCRIPTDIR}/adpn-ingest-test.defaults.conf"

PLUGINTXT=`mktemp`

declare -a _ARGV ; _ARGV=($0)
declare -A SUBARGV_AUNAME ; SUBARGV_AUNAME=()
declare -A SUBARGV_STAGEDLOCAL ; SUBARGV_STAGEDLOCAL=()
declare -A SUBARGV_LOCKSSPLUGINURL ; SUBARGV_LOCKSSPLUGINURL=()
declare -A SUBARGV_ADPNPLUGININFO ; SUBARGV_ADPNPLUGININFO=()
declare -A SUBARGV_LOCKSSRETRIEVEJAR ; SUBARGV_LOCKSSRETRIEVEJAR=()
declare -A SUBARGV_TESTURLOK ; SUBARGV_TESTURLOK=()

##########################################################################################
### DEPENDENCIES: check for required command-line tools and Python scripts ###############
##########################################################################################

declare -A DEPENDENCIES ; DEPENDENCIES=(
	[mktemp]="command-line %s tool"
	[grep]="command-line %s tool"
	[xargs]="command-line %s tool"
	[du]="command-line %s tool"
	[find]="command-line %s tool"
	[adpn-plugin-info]="%s Bash script"
	[lockss-plugin-url.py]="%s Python script"
	[lockss-retrieve-jar.py]="%s Python script"
	[lockss-plugin-props.py]="%s Python script"
	[lockss-plugin-props-print-parameter.py]="%s Python script"
	[adpn-ingest-test-url-ok.py]="%s Python script"
)

DEPENDENCY_FAILURE=""
for CMD in "${!DEPENDENCIES[@]}" ; do
	DESC=$(printf "${DEPENDENCIES[$CMD]}" "${CMD}")
	if [[ -z $(which ${CMD}) ]] ; then
		echo 1>&2
		echo Dependency Failure: ${CMD}. This script requires the ${DESC}. 1>&2
		DEPENDENCY_FAILURE="${DEPENDENCY_FAILURE}+${CMD}"
	fi
done

if [[ ! -z "${DEPENDENCY_FAILURE}" ]] ; then
	exit 1
fi

##########################################################################################
### COMMAND LINE: loop through switches and sort them to subsidiary scripts ##############
##########################################################################################

shopt -s lastpipe

declare -a SWITCHFILES ; SWITCHFILES=()
if [[ -r "${CONFFILE}" ]] ; then
	SWITCHFILES+=(${CONFFILE})
fi

CMDLINETXT=`mktemp`

if [[ "$1" == "-" ]] ; then
	./adpn-json-to-switches.py $1 >> "${CMDLINETXT}"
	shift
	
	cat "${CMDLINETXT}" | while IFS="" read -r SWITCH ; do
		_ARGV+=("${SWITCH}")
	done
fi

until [[ -z "$1" ]] ; do
	_ARGV+=("$1")
	printf "%s\n" "$1" >> "${CMDLINETXT}"
	shift
done

SWITCHFILES+=(${CMDLINETXT})

cat "${SWITCHFILES[@]}" | while IFS="" read -r SWITCH ; do

	if [[ "${SWITCH}" =~ ^--([A-Za-z_0-9][^=]*)=\s*(.*)\s*$ ]] ; then
		KEY="${BASH_REMATCH[1]}"
		VALUE="${BASH_REMATCH[2]}"
		
		case "${KEY}" in
			"jar")
				JAR="${VALUE}"
				;;
			"daemon"|"plugin"|"plugin-regex"|"plugin-keywords"|"plugin-id"|"user"|"pass")
				SUBARGV_LOCKSSPLUGINURL[$KEY]="--${KEY}=${VALUE}"
				;;
			"proxy"|"port"|"tunnel"|"tunnel-port")
				SUBARGV_LOCKSSRETRIEVEJAR[$KEY]="--${KEY}=${VALUE}"
				SUBARGV_TESTURLOK[$KEY]="--${KEY}=${VALUE}"
				;;
			"au_title")
				SUBARGV_AUNAME[$KEY]="${VALUE}"
				;;
			"local"|"remote")
				SUBARGV_STAGEDLOCAL[$KEY]="${VALUE}"
				;;
			*)
				SUBARGV_ADPNPLUGININFO[$KEY]="--${KEY}=${VALUE}"
				;;
		esac
		
	elif [[ ! -z "${SWITCH}" ]] ; then
		SUBARGV_ADPNPLUGININFO[$SWITCH]="${SWITCH}"
	fi
	
done

##########################################################################################
### USER INPUT: get missing parameters from the user console if not command line #########
##########################################################################################

if [[ -z "${SUBARGV_AUNAME[au_title]}" ]] ; then
	read -r -p "Ingest Name/Title: " AU_TITLE
	_ARGV+=("--au_title=${AU_TITLE}")
	SUBARGV_AUNAME[au_title]="${AU_TITLE}"
fi

if [[ -z "${SUBARGV_STAGEDLOCAL[local]}" && -z "${SUBARGV_STAGEDLOCAL[remote]}" ]] ; then
	read -r -p "Local file location: " LOCALPATH
	_ARGV+=("--local=${LOCALPATH}")
	SUBARGV_STAGEDLOCAL[local]="${LOCALPATH}"
fi

if [[
	-z "${JAR}"
	&& -z "${SUBARGV_LOCKSSPLUGINURL[plugin]}" 
	&& -z "${SUBARGV_LOCKSSPLUGINURL[plugin-regex]}" 
	&& -z "${SUBARGV_LOCKSSPLUGINURL[plugin-keywords]}" 
	&& -z "${SUBARGV_LOCKSSPLUGINURL[plugin-id]}" 
]] ; then
	read -r -p "Publisher Plugin (keywords): " PUBLISHERPLUGIN
	_ARGV+=("--plugin-keywords=${PUBLISHERPLUGIN}")
	SUBARGV_LOCKSSPLUGINURL[plugin-keywords]="--plugin-keywords=${PUBLISHERPLUGIN}"
fi

if [[ -z "${SUBARGV_LOCKSSPLUGINURL[daemon]}" ]] ; then
	read -r -p "LOCKSS Daemon Server: " DAEMON
	_ARGV+=("--daemon=${DAEMON}")
	SUBARGV_LOCKSSPLUGINURL[daemon]="--daemon=${DAEMON}"
fi

if [[ -z "${SUBARGV_LOCKSSPLUGINURL[user]}" ]] ; then
	read -r -p "LOCKSS Daemon Username: " DAEMONUSER
	_ARGV+=("--user=${DAEMONUSER}")
	SUBARGV_LOCKSSPLUGINURL[user]="--user=${DAEMONUSER}"
fi

if [[ -z "${SUBARGV_LOCKSSPLUGINURL[pass]}" ]] ; then
	read -r -s -p "LOCKSS Daemon Password: " DAEMONPASS ; echo
	_ARGV+=("--pass=${DAEMONPASS}")
	SUBARGV_LOCKSSPLUGINURL[pass]="--pass=${DAEMONPASS}"
fi

##########################################################################################
### lockss-plugin-url.py: Retrieve URL of the Plugin JAR package. ########################
##########################################################################################

if [[ -z "${JAR}" ]] ; then
	JAR=`lockss-plugin-url.py "${SUBARGV_LOCKSSPLUGINURL[@]}"`
fi

if [ -z "${JAR}" ] ; then

	echo "[${SCRIPT}] No Publisher Plugin matches ${SUBARGV_LOCKSSPLUGINURL[@]}." 1>&2

elif [ "$?" -eq 2 ] ; then

	echo ""
	echo "MULTIPLE MATCHING PLUGINS:"
	echo "=========================="
	echo "${JAR}"
	
elif [ ! -z "${JAR}" ] ; then


	if [ ! -z "${SUBARGV_STAGEDLOCAL[local]}" ] ; then

		DU_BYTES=`du --human-readable --apparent-size --bytes "${SUBARGV_STAGEDLOCAL[local]}" | cut -f1`
		DU_BYTES=$(printf "%'d" "${DU_BYTES}")

		DU_HUMANREADABLE=`du --human-readable --apparent-size --human-readable --max-depth=0 "${SUBARGV_STAGEDLOCAL[local]}" | cut -f1`

		FIND_FILECOUNT=$(find "${SUBARGV_STAGEDLOCAL[local]}" | wc -l)

	fi

	if [[ ! -z "${SUBARGV_AUNAME[@]}" ]] ; then
		echo "Ingest Title	${SUBARGV_AUNAME[@]}" >> ${PLUGINTXT}
	fi
	if [[ ! -z "${SUBARGV_STAGEDLOCAL[local]}" ]] ; then
		echo "File Size 	${DU_HUMANREADABLE} (${DU_BYTES} bytes, ${FIND_FILECOUNT} files)" >> ${PLUGINTXT}
	fi

######################################################################################
	### lockss-plugin-url.py | adpn-plugin-info: Retrieve & analyze Plugin JAR. ##########
	######################################################################################

	lockss-retrieve-jar.py --url="${JAR}" "${SUBARGV_LOCKSSRETRIEVEJAR[@]}" | adpn-plugin-info - --quiet --format=text/tab-separated-values --jar="${JAR}" "${SUBARGV_ADPNPLUGININFO[@]}" >> ${PLUGINTXT}
	LOCKSSRETRIEVEJAR=$?

	echo ""
	if [[ "${LOCKSSRETRIEVEJAR}" -eq 0 ]] ; then
		echo "INGEST INFORMATION AND PARAMETERS:"
		echo "----------------------------------"
	else 
		echo "INGEST INFORMATION:"
		echo "-------------------"
	fi

	grep -P '^Ingest Title' ${PLUGINTXT} | lockss-plugin-props-print-parameter.py
	grep -P '^File Size' ${PLUGINTXT} | lockss-plugin-props-print-parameter.py
	grep -P '^Plugin (JAR|Name|Version|ID)' ${PLUGINTXT} | lockss-plugin-props-print-parameter.py
	if [[ "${LOCKSSRETRIEVEJAR}" -eq 0 ]] ; then
		grep -P "^PARAM[(].*[)]:\t" ${PLUGINTXT} | lockss-plugin-props-print-parameter.py
	fi
	
	######################################################################################
	### adpn-ingest-test-url-ok.py: if all Plugin Parameters provided, test URLs OK ####
	######################################################################################

	if [[ "${LOCKSSRETRIEVEJAR}" -eq 0 ]] ; then
		echo ""
		echo -n "JSON PACKET:	"
		cat ${PLUGINTXT} | lockss-plugin-props-print-parameter.py --output=application/json
		
		echo ""
		echo "URL RETRIEVAL TESTS:"
		echo "--------------------"
		( cat ${PLUGINTXT} | grep -P '^au_start_url\t' | adpn-ingest-test-url-ok.py "${SUBARGV_TESTURLOK[@]}" ) || ERROR_ON="${ERROR_ON} au_start_url"
		( cat ${PLUGINTXT} | grep -P '^au_manifest\t' | adpn-ingest-test-url-ok.py "${SUBARGV_TESTURLOK[@]}" ) || ERROR_ON="${ERROR_ON} au_manifest"		
		
	else
	
		echo ""
		echo "REQUIRED PARAMETERS:"
		echo "--------------------"
		grep -P "^PARAM[(].*[)]:\t" ${PLUGINTXT} | lockss-plugin-props-print-parameter.py
		
		echo ""
		read -n1 -p "Read from console (Y/N)? " PARAMS_YN ; echo ""
		
		if [[ "${PARAMS_YN}" == "Y" || "${PARAMS_YN}" == "y" ]] ; then
			
			echo ""
			
			declare -a PLUGIN_LINE
			
			PARAMS_IN=`mktemp`
			PARAMS_SWITCHES=`mktemp`
			
			for idx in ${!_ARGV[@]} ; do
				if (( "${idx}" > 0 )) ; then
					printf "%s\n" "${_ARGV[$idx]}" >> ${PARAMS_SWITCHES}
				fi
			done
			
			grep -P "^PARAM[(].*[)]:\t" ${PLUGINTXT} > ${PARAMS_IN}
			while read -r -u3 -a PLUGIN_LINE ; do
				if [[ ! "${PLUGIN_LINE[1]}" =~ .*=.* ]] ; then
					read -p "${PLUGIN_LINE[0]} ${PLUGIN_LINE[1]}: " PARAM_VALUE
					echo "--${PLUGIN_LINE[1]}=${PARAM_VALUE}" >> "${PARAMS_SWITCHES}"
				fi
			done 3<"${PARAMS_IN}"
			
			xargs -a "${PARAMS_SWITCHES}" --delimiter='\n' "${_ARGV[0]}"
			
			rm "${PARAMS_IN}"
			rm "${PARAMS_SWITCHES}"
		fi
	fi
fi

##########################################################################################
### ERRORS: List any errors reported by subsidiary scripts ###############################
##########################################################################################

if [ ! -z "${ERROR_ON}" ] ; then

	echo ""
	echo "INGEST TEST ERRORS:"
	echo "-------------------"
	for mod in ${ERROR_ON} ; do
		echo "Failed: ${mod}"
	done
fi

##########################################################################################
### CLEANUP: remove temporary output file ################################################
##########################################################################################

rm ${PLUGINTXT}
rm ${CMDLINETXT}
