#!/bin/bash
#
# adpn-do-preserve-email: As part of the ingest process, accept some pipelined JSON data
# from stdin, and then drop it into an e-mail to the network admin.
#
# Usage: <INPUT> | adpn-do-preserve-email --subject="<SUBJECT_LINE>" [--to="<EMAIL>"]
#
# - Attempts to find an OUTLOOK.EXE, and if found, uses command-line parameters to spawn
#   a new e-mail with the specified e-mail address, subject line and body.
#
# @version 2019.0807

SCRIPTPATH=$(which "$0")
SCRIPTDIR=$(dirname "${SCRIPTPATH}")
SCRIPTNAME=$(basename "${SCRIPTPATH}")

EXITCODE=0

source "${SCRIPTDIR}/adpn-define-aliases"

##########################################################################################
### COMMAND LINE: loop through switches and sort them to subsidiary scripts ##############
##########################################################################################

shopt -s lastpipe

declare -a SWITCHFILES ; SWITCHFILES=()
declare -a _ARGV ; _ARGV=()
declare -A _PARAM ; _PARAM=()

CMDLINETXT=$(mktemp)

until [[ -z "$1" ]] ; do
	printf "%s\n" "$1" >> "${CMDLINETXT}"
	shift
done

SWITCHFILES+=(${CMDLINETXT})

cat "${SWITCHFILES[@]}" | while IFS="" read -r SWITCH ; do

	if [[ "${SWITCH}" =~ ^--([A-Za-z_0-9][^=]*)(=\s*(.*)\s*)?$ ]] ; then
		KEY="${BASH_REMATCH[1]}"
		VALUE="${BASH_REMATCH[3]}"
		if [[ -z "${BASH_REMATCH[2]}" ]] ; then
			VALUE="${KEY}"
		fi

		_PARAM[$KEY]="${VALUE}"
		
	elif [[ ! -z "${SWITCH}" ]] ; then
		_ARGV+=("${SWITCH}")
	fi
	
done

rm "${CMDLINETXT}"

##########################################################################################
### SCRIPT: Get admin e-mail address, subject, and body from config, cmd line or stdin ###
##########################################################################################

VV="${_LINESWITCH[verbose]}"
QQ="${_LINESWITCH[quiet]}"
V="${_LINESWITCH[verbose]}"
Q=""

DBG="${_LINESWITCH[debug]}"
DBGLEVEL="${_PARAM[debug]}"
if [[ "${DBGLEVEL}" == "debug" ]] ; then
	DBGLEVEL=1
fi
if [[ "${DBGLEVEL}" -gt 1 ]] ; then
	DBGLEVEL=$(( DBGLEVEL - 1 ))
	DDBG="--debug=${DBGLEVEL}"
else
	DDBG=""
fi

if [[ -z "${_PARAM[verbose]}" ]] ; then
	Q="--quiet"
fi
if [[ -n "${QQ}" ]] ; then
	Q="--quiet"
fi

[ ! -z "${_PARAM[to]}" ] && ADMIN_EMAIL="${_PARAM[to]}" || ADMIN_EMAIL=$(adpnprop preserve/admin-email)
[ ! -z "${_PARAM[subject]}" ] && SUBJECT_TEXT="${_PARAM[subject]}" || SUBJECT_TEXT="ADPNet Ingest"

PIPED_TEXT="$( cat "${_ARGV[@]}" )"
PRETTY_JSON="$( printf "%s" "${PIPED_TEXT}" | adpn-json.py --output=application/json --indent=2 )"
DEFAULT_REPOSITORY="$( adpnprop gitlab/repository )"
USER_NAME="$( printf "%s" "${PIPED_TEXT}" | adpn-json.py --key="Staged By" )"
DIRECTORY="${_PARAM[subdirectory]}"

IFS='' read -r -d '' BODY_TEXT <<EOText
${USER_NAME} used the \`adpn\` CLI tool to upload files for an ADPNet ingest to the ${LOCATION} staging area, directory: \`${DIRECTORY}\`.

AU meta-data output by \`adpn preserve\` follows:

~~~
${PIPED_TEXT}
~~~

Pretty-printed JSON packet:

~~~
${PRETTY_JSON}
~~~

This ticket has been created automatically by the \`adpn preserve\` command to notify ADPNet Techs that the AU has been staged and is ready to be tested for ingest, and to provide a place to track the work of adding the new AU to the config server.
EOText

#ADMIN_EMAIL=$( rawurlencode "${ADMIN_EMAIL}" )
#SUBJECT_TEXT=$( rawurlencode "${SUBJECT_TEXT}" )
#BODY_TEXT=$( rawurlencode "${BODY_TEXT}" )

printf "%s" "${BODY_TEXT}" | adpn-do-gitlab issue --post --title="${SUBJECT_TEXT}" --pipe=description --project="${DEFAULT_REPOSITORY}" ${V} ${DDBG}
EXITCODE="$?"

##########################################################################################
### SCRIPT: Look to see if Outlook.exe is available. #####################################
##########################################################################################

#OUTLOOK=$( which OUTLOOK.EXE 2> /dev/null )
#if [[ -z "${OUTLOOK}" ]] ; then
#	CYGPATH=$( which cygpath 2> /dev/null )
#	if [[ ! -z "${CYGPATH}" ]] ; then
#		OUTLOOK="$(cygpath "${PROGRAMFILES}\Microsoft Office\root\Office16\OUTLOOK.EXE")"
#		if [[ -z "${OUTLOOK}" || ! -x "${OUTLOOK}" ]] ; then
#			OUTLOOK="$(cygpath "${PROGRAMFILES} (x86)\Microsoft Office\root\Office16\OUTLOOK.EXE")"
#		else :
#			printf "[%s:79] Could not track down Outlook.exe\n" "${SCRIPTNAME}" 1>&2
#		fi
#	else :
#		printf "[%s:82] cygpath is not available\n" "${SCRIPTNAME}" 1>&2
#	fi
#fi

##########################################################################################
### SCRIPT: If Outlook.exe is available, use it to spin up an e-mail. ####################
##########################################################################################

#if [[ ! -z "${OUTLOOK}" && -x "${OUTLOOK}" ]] ; then
#	"${OUTLOOK}" /c ipm.note /m "mailto:${ADMIN_EMAIL}&subject=${SUBJECT_TEXT}&body=${BODY_TEXT}"
#else :
#	printf "[%s:93] Could not launch Outlook.exe\n" "${SCRIPTNAME}" 1>&2
#	EXITCODE=1
#fi

exit "${EXITCODE}"
